#CONFIG.YAML
#MAKE SURE THAT ITS IN THE SAME DIRECTORY AS THE SCRIPT

# Change the alarm completion sound here
# Ensure that the sound is in a mp3 or wav file format - otherwise it wont work
soundPath: "./sound.wav"
soundRequired: False # if you want to play a sound, after the timer change this to true
alarmDoneTxt: boombayah the alarms done # Change the text, which is printed out when the alarm is done

# You can change the digits here, or how the menu looks
ascii:
  digits:
    "0":
      - "███"
      - "█ █"
      - "█ █"
      - "█ █"
      - "███"
    "1":
      - "  █"
      - "  █"
      - "  █"
      - "  █"
      - "  █"
    "2":
      - "███"
      - "  █"
      - "███"
      - "█  "
      - "███"
    "3":
      - "███"
      - "  █"
      - "███"
      - "  █"
      - "███"
    "4":
      - "█ █"
      - "█ █"
      - "███"
      - "  █"
      - "  █"
    "5":
      - "███"
      - "█  "
      - "███"
      - "  █"
      - "███"
    "6":
      - "███"
      - "█  "
      - "███"
      - "█ █"
      - "███"
    "7":
      - "███"
      - "  █"
      - "  █"
      - "  █"
      - "  █"
    "8":
      - "███"
      - "█ █"
      - "███"
      - "█ █"
      - "███"
    "9":
      - "███"
      - "█ █"
      - "███"
      - "  █"
      - "███"
    ":":
      - "   "
      - " █ "
      - "   "
      - " █ "
      - "   "
    " ":
      - "   "
      - "   "
      - "   "
      - "   "
      - "   "
    clock:
      - "._________________._________________._________________._________________."
      - "|                 |                 |                 |                 |"
      - "| >>   Clock   << |    Stopwatch    |      Alarm      |     Credits     |"
      - "|                 |                 |                 |                 |"
      - "'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'"
    timer:
      - "._________________._________________._________________._________________."
      - "|                 |                 |                 |                 |"
      - "|      Clock      | >> Stopwatch << |      Alarm      |     Credits     |"
      - "|                 |                 |                 |                 |"
      - "'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'"
    alarm:
      - "._________________._________________._________________._________________."
      - "|                 |                 |                 |                 |"
      - "|      Clock      |    Stopwatch    |  >>  Alarm  <<  |     Credits     |"
      - "|                 |                 |                 |                 |"
      - "'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'"
    face:
      - "._________________._________________._________________._________________."
      - "|                 |                 |                 |                 |"
      - "|      Clock      |    Stopwatch    |      Alarm      | >>  Credits  << |"
      - "|                 |                 |                 |                 |"
      - "'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾'"
